server:
  port: 8080

spring:
  application:
    name: expense-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: expense
    password: expense
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always